// export const CREATE_ORDER_REQUEST='CREATE_ORDER_REQUEST';
// export const CREATE_ORDER_SUCCESS='CREATE_ORDER_SUCCESS';
// export const CREATE_ORDER_FALIURE='CREATE_ORDER_FALIURE';

// export const GET_ORDER_BY_ID_REQUEST='GET_ORDER_BY_ID_REQUEST';
// export const GET_ORDER_BY_ID_SUCCESS='GET_ORDER_BY_ID_SUCCESS';
// export const GET_ORDER_BY_ID_FALIURE='GET_ORDER_BY_ID_FALIURE';
// export const SET_SHIPPING_ADDRESS = "SET_SHIPPING_ADDRESS"

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FALIURE = 'CREATE_ORDER_FALIURE';

export const GET_ORDER_BY_ID_REQUEST = 'GET_ORDER_BY_ID_REQUEST';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS';
export const GET_ORDER_BY_ID_FALIURE = 'GET_ORDER_BY_ID_FALIURE';

// ✅ New — fetch all orders for current user (order history page)
export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST';
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FALIURE = 'GET_ALL_ORDERS_FALIURE';

export const SET_SHIPPING_ADDRESS = "SET_SHIPPING_ADDRESS";