export const CREATE_ORDER_REQUEST='CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS='CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FALIURE='CREATE_ORDER_FALIURE';

export const GET_ORDER_BY_ID_REQUEST='GET_ORDER_BY_ID_REQUEST';
export const GET_ORDER_BY_ID_SUCCESS='GET_ORDER_BY_ID_SUCCESS';
export const GET_ORDER_BY_ID_FALIURE='GET_ORDER_BY_ID_FALIURE';