export const SAVE_PAYMENT_REQUEST  = "SAVE_PAYMENT_REQUEST";
export const SAVE_PAYMENT_SUCCESS  = "SAVE_PAYMENT_SUCCESS";
export const SAVE_PAYMENT_FAILURE  = "SAVE_PAYMENT_FAILURE";

export const GET_PAYMENTS_REQUEST  = "GET_PAYMENTS_REQUEST";
export const GET_PAYMENTS_SUCCESS  = "GET_PAYMENTS_SUCCESS";
export const GET_PAYMENTS_FAILURE  = "GET_PAYMENTS_FAILURE";